webtalk_init -webtalk_dir D:/myWorkspace/MOKArian/github/event_stream_processor/scripts/sim/uart_tx_test/uart_tx_test/uart_tx_test.sim/sim_1/behav/xsim/xsim.dir/tb_uart_tx_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 25 10:14:52 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6eec6e06-9044-4e5d-912e-ce6b6dad496d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "22d6ea08791b46b58302c99ba905291f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "74" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 7445HS w/ Radeon 740M Graphics     " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9512_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4261949179 -regid "" -xml D:/myWorkspace/MOKArian/github/event_stream_processor/scripts/sim/uart_tx_test/uart_tx_test/uart_tx_test.sim/sim_1/behav/xsim/xsim.dir/tb_uart_tx_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/myWorkspace/MOKArian/github/event_stream_processor/scripts/sim/uart_tx_test/uart_tx_test/uart_tx_test.sim/sim_1/behav/xsim/xsim.dir/tb_uart_tx_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/myWorkspace/MOKArian/github/event_stream_processor/scripts/sim/uart_tx_test/uart_tx_test/uart_tx_test.sim/sim_1/behav/xsim/xsim.dir/tb_uart_tx_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
